// Auto-generated from app.html.
// DO NOT EDIT.

library tile2atlas_app;

import 'dart:html' as autogenerated;
import 'dart:svg' as autogenerated_svg;
import 'package:web_ui/web_ui.dart' as autogenerated;
import 'package:web_ui/observe/observable.dart' as __observe;
import 'navbar.html.dart';
import 'tileset-choose.dart';
import 'tileset-configure.dart';
import 'tileset-export.dart';
import 'package:web_ui/web_ui.dart';
import 'dart:html';
import 'src/model.dart';



class Tile2atlasApp extends WebComponent {
  /** Autogenerated from the template. */

  autogenerated.ScopedCssMapper _css;

  /** This field is deprecated, use getShadowRoot instead. */
  get _root => getShadowRoot("tile2atlas-app");
  static final __html1 = new autogenerated.Element.html('<div is="x-tileset-choose"></div>'), __html2 = new autogenerated.Element.html('<div is="x-tileset-configure"></div>'), __html3 = new autogenerated.Element.html('<div is="x-tileset-export"></div>'), __shadowTemplate = new autogenerated.DocumentFragment.html('''
  <section>
    <header>
      <div is="x-nav-bar"></div>
    </header>
    <section id="view" class="container">
      <template></template>
      <template></template>
      <template></template>
    </section>
  </section>
''');
  autogenerated.DivElement __e1;
  autogenerated.Element __e3, __e5, __e7;
  autogenerated.Template __t;

  void created_autogenerated() {
    var __root = createShadowRoot("tile2atlas-app");
    setScopedCss("tile2atlas-app", new autogenerated.ScopedCssMapper({"tile2atlas-app":"[is=\"tile2atlas-app\"]"}));
    _css = getScopedCss("tile2atlas-app");
    __t = new autogenerated.Template(__root);
    __root.nodes.add(__shadowTemplate.clone(true));
    __e1 = __root.nodes[1].nodes[1].nodes[1];
    __t.oneWayBind(() => app.titre, (e) { if (__e1.xtag.titre != e) __e1.xtag.titre = e; }, false, false);
    __t.component(new NavBar()..host = __e1);
    __e3 = __root.nodes[1].nodes[3].nodes[1];
    __t.conditional(__e3, () => app.currentView == ViewEnum.CHOOSE, (__t) {
      var __e2;
      __e2 = __html1.clone(true);
      __t.component(new TilesetChoose()..host = __e2);
    __t.addAll([new autogenerated.Text('\n        '),
        __e2,
        new autogenerated.Text('\n      ')]);
    });

    __e5 = __root.nodes[1].nodes[3].nodes[3];
    __t.conditional(__e5, () => app.currentView == ViewEnum.CONFIGURE, (__t) {
      var __e4;
      __e4 = __html2.clone(true);
      __t.component(new TilesetConfigure()..host = __e4);
    __t.addAll([new autogenerated.Text('\n        '),
        __e4,
        new autogenerated.Text('\n      ')]);
    });

    __e7 = __root.nodes[1].nodes[3].nodes[5];
    __t.conditional(__e7, () => app.currentView == ViewEnum.EXPORT, (__t) {
      var __e6;
      __e6 = __html3.clone(true);
      __t.component(new TilesetExport()..host = __e6);
    __t.addAll([new autogenerated.Text('\n        '),
        __e6,
        new autogenerated.Text('\n      ')]);
    });

    __t.create();
  }

  void inserted_autogenerated() {
    __t.insert();
  }

  void removed_autogenerated() {
    __t.remove();
    __t = __e1 = __e3 = __e5 = __e7 = null;
  }

  /** Original code from the component. */


  Tile2atlasApp() {
    app.tileset.image.onLoad.listen(_onTilesetLoad);
  }

  void _onTilesetLoad(Event e) {
    app.currentView = ViewEnum.CONFIGURE;
  }
}
//# sourceMappingURL=app.dart.map