// Auto-generated from index.html.
// DO NOT EDIT.

library index_html;

import 'dart:html' as autogenerated;
import 'dart:svg' as autogenerated_svg;
import 'package:web_ui/web_ui.dart' as autogenerated;
import 'package:web_ui/observe/observable.dart' as __observe;
import 'app.dart';


// Original code
void main() {/*useShadowDom = true;*/}
// Additional generated code
void init_autogenerated() {
  var __root = autogenerated.document.body;
  var __e0;
  var __t = new autogenerated.Template(__root);
  __e0 = __root.nodes[1];
  __t.component(new Tile2atlasApp()..host = __e0);
  __t.create();
  __t.insert();
}

//# sourceMappingURL=index.html.dart.map