// Auto-generated from navbar.html.
// DO NOT EDIT.

library x_nav_bar;

import 'dart:html' as autogenerated;
import 'dart:svg' as autogenerated_svg;
import 'package:web_ui/web_ui.dart' as autogenerated;
import 'package:web_ui/observe/observable.dart' as __observe;
import 'package:web_ui/web_ui.dart';



  class NavBar extends WebComponent {
  /** Autogenerated from the template. */

  autogenerated.ScopedCssMapper _css;

  /** This field is deprecated, use getShadowRoot instead. */
  get _root => getShadowRoot("x-nav-bar");
  static final __shadowTemplate = new autogenerated.DocumentFragment.html('''
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="brand" href="#"></a>
        <content></content>
      </div>
    </div>
  </div>
''');
  autogenerated.AnchorElement __e9;
  autogenerated.Template __t;

  void created_autogenerated() {
    var __root = createShadowRoot("x-nav-bar");
    setScopedCss("x-nav-bar", new autogenerated.ScopedCssMapper({"x-nav-bar":"[is=\"x-nav-bar\"]"}));
    _css = getScopedCss("x-nav-bar");
    __t = new autogenerated.Template(__root);
    __root.nodes.add(__shadowTemplate.clone(true));
    __e9 = __root.nodes[1].nodes[1].nodes[1].nodes[1];
    var __binding8 = __t.contentBind(() => titre, false);
    __e9.nodes.add(__binding8);
    __t.create();
  }

  void inserted_autogenerated() {
    __t.insert();
  }

  void removed_autogenerated() {
    __t.remove();
    __t = __e9 = null;
  }

  /** Original code from the component. */

    String titre;
  }

//# sourceMappingURL=navbar.html.dart.map