// Auto-generated from tileset-choose.html.
// DO NOT EDIT.

library x_tileset_choose;

import 'dart:html' as autogenerated;
import 'dart:svg' as autogenerated_svg;
import 'package:web_ui/web_ui.dart' as autogenerated;
import 'package:web_ui/observe/observable.dart' as __observe;
import 'package:web_ui/web_ui.dart';
import 'dart:html';
import 'src/model.dart';



class TilesetChoose extends WebComponent {
  /** Autogenerated from the template. */

  autogenerated.ScopedCssMapper _css;

  /** This field is deprecated, use getShadowRoot instead. */
  get _root => getShadowRoot("x-tileset-choose");
  static final __shadowTemplate = new autogenerated.DocumentFragment.html('''
  <div class="hero-unit">
    <h1>Choose a Tileset</h1>
    <p>Simple tool for generate a Json texture atlas from an image Tileset.</p>
    <form>
      <input type="file" id="tileset-chooser" class="btn btn-primary btn-large">
    </form>
  </div>
''');
  autogenerated.InputElement __e10;
  autogenerated.Template __t;

  void created_autogenerated() {
    var __root = createShadowRoot("x-tileset-choose");
    setScopedCss("x-tileset-choose", new autogenerated.ScopedCssMapper({"x-tileset-choose":"[is=\"x-tileset-choose\"]"}));
    _css = getScopedCss("x-tileset-choose");
    __t = new autogenerated.Template(__root);
    __root.nodes.add(__shadowTemplate.clone(true));
    __e10 = __root.nodes[1].nodes[5].nodes[1];
    __t.listen(__e10.onChange, ($event) { loadTileset(); });
    __t.create();
  }

  void inserted_autogenerated() {
    __t.insert();
  }

  void removed_autogenerated() {
    __t.remove();
    __t = __e10 = null;
  }

  /** Original code from the component. */

  InputElement _chooser;
  FileReader _reader;

  TilesetChoose() {
    _reader = new FileReader();
    _reader.onLoad.listen(_onReaderComplete);
  }

  void inserted() {
    _chooser = this.query("#tileset-chooser");
  }

  void loadTileset() {
    if (_chooser.files.length > 0) {
      _reader.readAsDataUrl(_chooser.files[0]);
    }
  }

  void _onReaderComplete(ProgressEvent event) {
    app.tileset.image.src = _reader.result;
  }
}
//# sourceMappingURL=tileset-choose.dart.map